# 5. Python Homework# Section 5 Python Homework

<br>

1. What does Pandas stand for?
    * Panel Data 
1. What are the 2 collections used in Pandas?
    * Series & DataFrame
1. Name 4 things Pandas can do for us.
    * Data Cleansing, Data inspection, Statistical analysis, and data visualization. 
1. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
    * values
1. What is a CSV
    * comma seperated value file
1. When cleaning data what values do we not like in our data?
    * Nulls
<br>

In [4]:
# Week 5 Homework Coding Exercise 

# 1. Concatenate these 3 arrays into a new array named 'newArray'...
'''([[25, 16]])
        ([[11, 2], [13, 4]])
        ([[7, 81], [5, 6], [11, 12]])
        '''
import numpy  as np 
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate([array1, array2, array3], axis=0)
print("\nnewArray ...\n", newArray)

# 2. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\nsortedArray...\n", sortedArray)

# 3. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2, 2, 3)
print("\nreshapedArray...\n", reshapedArray)

# 4. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

unpacked = reshapedArray.reshape(4, 3)
print("\nunpacked...\n", unpacked)

a, b, c, d = unpacked

print("a = ", a)
print("b = ", b)
print("c = ", c)
print("d = ", d)



newArray ...
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

sortedArray...
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

reshapedArray...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

unpacked...
 [[16 25  2]
 [11  4 13]
 [ 7 81  5]
 [ 6 11 12]]
a =  [16 25  2]
b =  [11  4 13]
c =  [ 7 81  5]
d =  [ 6 11 12]


In [8]:
# 5 Combine and sort the following arrays into one called 'comboArray' ...

''' one = ([10, 11, 12, 13, 14, 15, 16, 17])
    two = ([20, 21, 22, 23, 24, 25, 26, 27])
    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    '''
    
import numpy as np 
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))
print("\ncomboArray...\n", comboArray)
# 6. Take 'comboArray' and perform the following slicing activities:
'''print sec1 - the 2nd element
print sec2 - all elements from the 3rd element to the last
print sec3 - all elements from the 4th to the 14th elements
print sec4 - the last 6 elements
print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print sec6 - from #20 every even element to the end
print sec7 - from the last element moving forward, every 5th element.
''' 

sec1 = comboArray[2]
print("\nThe 2nd element is ...", sec1)

sec2 = comboArray[3:]
print("\n All elements from 3rd to last...", sec2)

sec3 = comboArray[4:15]
print("\n All elements from 4th to the 14th...", sec3)

sec4 = comboArray[-6:]
print('\n The last 6 elements...', sec4)

sec5 = comboArray[:-10]
print('\n All element from #0 up to and including #15...', sec5)

sec6 = comboArray[::2]
print('\n From #20 every even element to the end...', sec6)


comboArray...
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

The 2nd element is ... 2

 All elements from 3rd to last... [ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

 All elements from 4th to the 14th... [ 4  5  6  7 10 11 12 13 14 15 16]

 The last 6 elements... [22 23 24 25 26 27]

 All element from #0 up to and including #15... [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]

 From #20 every even element to the end... [21 23 25 27]
