# 5. Python Homework# Section 5 Python Homework

<br>

1. What does Pandas stand for?
    * Panel Data 
1. What are the 2 collections used in Pandas?
    * Series & DataFrame
1. Name 4 things Pandas can do for us.
    * Data Cleansing, Data inspection, Statistical analysis, and data visualization. 
1. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
    * values
1. What is a CSV
    * comma seperated value file
1. When cleaning data what values do we not like in our data?
    * Nulls
<br>

In [11]:
# Week 5 Homework Coding Exercise 

# 1. Concatenate these 3 arrays into a new array named 'newArray'...
'''([[25, 16]])
        ([[11, 2], [13, 4]])
        ([[7, 81], [5, 6], [11, 12]])
        '''
import numpy  as np 
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate([array1, array2, array3], axis=0)
print("\nnewArray ...\n", newArray)

# 2. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\nsortedArray...\n", sortedArray)

# 3. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2, 2, 3)
print("\nreshapedArray...\n", reshapedArray)

# 4. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

unpacked = reshapedArray.reshape(4, 3)
print("\nunpacked...\n", unpacked)

a, b, c, d = unpacked

print("a = ", a)
print("b = ", b)
print("c = ", c)
print("d = ", d)



newArray ...
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

sortedArray...
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

reshapedArray...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

unpacked...
 [[16 25  2]
 [11  4 13]
 [ 7 81  5]
 [ 6 11 12]]
a =  [16 25  2]
b =  [11  4 13]
c =  [ 7 81  5]
d =  [ 6 11 12]


In [12]:
# 5 Combine and sort the following arrays into one called 'comboArray' ...

''' one = ([10, 11, 12, 13, 14, 15, 16, 17])
    two = ([20, 21, 22, 23, 24, 25, 26, 27])
    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    '''
    
import numpy as np 
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))
print("\ncomboArray...\n", comboArray)
# 6. Take 'comboArray' and perform the following slicing activities:
'''print sec1 - the 2nd element
print sec2 - all elements from the 3rd element to the last
print sec3 - all elements from the 4th to the 14th elements
print sec4 - the last 6 elements
print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print sec6 - from #20 every even element to the end
print sec7 - from the last element moving forward, every 5th element.
''' 

sec1 = comboArray[2]
print("\nThe 2nd element is ...", sec1)

sec2 = comboArray[3:]
print("\n All elements from 3rd to last...", sec2)

sec3 = comboArray[4:15]
print("\n All elements from 4th to the 14th...", sec3)

sec4 = comboArray[-6:]
print('\n The last 6 elements...', sec4)

sec5 = comboArray[:-10]
print('\n All element from #0 up to and including #15...', sec5)

sec6 = comboArray[16::2]
print('\n From #20 every even element to the end...', sec6)

sec7 = comboArray[-1::-5]
print('From the last element moving forward, every 5th element...', sec7)


comboArray...
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

The 2nd element is ... 2

 All elements from 3rd to last... [ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

 All elements from 4th to the 14th... [ 4  5  6  7 10 11 12 13 14 15 16]

 The last 6 elements... [22 23 24 25 26 27]

 All element from #0 up to and including #15... [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]

 From #20 every even element to the end... [20 22 24 26]
From the last element moving forward, every 5th element... [27 22 15 10  3]


In [14]:
# 7. Using simple math operations, broadcast the addition `(+)`, division `(/)`, and multiplication `(*)` operations for these 2 arrays --

'''python
    ([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

    ([[17.0, 70.0, 10.7]])
'''

from numpy import array

array_1= array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
    [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
    [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])
array_2= array([[17.0, 70.0, 10.7]])

print('\nAddition:\n', array_1 + array_2)
print("\nDivision:\n", array_1 / array_2)
print("\nMultiplication:\n", array_1 * array_2)

#8 Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.
import numpy as np
arr2 = np.subtract(array_1, array_2)
print("\nSubtraction ...\n", arr2)

#9 Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
divisible_by_3 = array_1[array_1 % 3 == 0]
print("array_1 elements divisible_by_3 ...", divisible_by_3)


Addition:
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

Division:
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

Multiplication:
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

Subtraction ...
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]
array_1 elements divisible_by_3 ... [ 0.  0. 30. 24. 15.]


In [34]:
#10 Using Series, create a DataFrame that looks like this:

import pandas as pd 

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
Quantity = pd.Series(["4", "1", "2", "1"], name ="Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

Dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)


print(Dinner)



  Ingredients Quantity   Unit
0       Flour        4   cups
1        Milk        1    cup
2        Eggs        2  large
3        Spam        1    can


In [43]:
# 11. Take this data and create a DataFrame named studentData

studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(studentData)
studentData.name = 'studentData'
print('\nDataframe names: studentData:\n', studentData)

# 12. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData.insert(7, "deserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"],True)
print("\nStudentData with deserts inserted as column 7...\n", studentData)

# 13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ["Name", "address"], inplace = True)
print("\nstudentData sorting by column Name and then address ...\n", studentData)







Dataframe names: studentData:
       Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

StudentData with deserts inserted as column 7...
       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  

studentData sorting by column Name and then address ...
    

In [52]:
# 14. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

# 15. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

veggies = pd.DataFrame([['turnip', 'potato'], ['silverbeet', 'yam']],
                        columns =['leafy green', 'root'])

veggies
veggies.to_csv('veggies.csv')

df = pd.read_csv('veggies.csv')
print(df)

veggies = pd.DataFrame([['turnip', 'potato'], ['silverbeet', 'yam']],
                        columns =['leafy green', 'root'])

veggies.to_csv('veggies.csv', index=False)
df = pd.read_csv('veggies.csv')
print(df)


                            

   Unnamed: 0 leafy green    root
0           0      turnip  potato
1           1  silverbeet     yam
  leafy green    root
0      turnip  potato
1  silverbeet     yam
